# An example of what a tweet looks like from the tweetstream gem

sample = {:in_reply_to_user_id=>nil,
 :user=>
  {:show_all_inline_media=>false,
   :notifications=>nil,
   :profile_text_color=>"333333",
   :follow_request_sent=>nil,
   :is_translator=>false,
   :profile_image_url=>
    "http://a0.twimg.com/sticky/default_profile_images/default_profile_5_normal.png",
   :screen_name=>"testrps",
   :profile_use_background_image=>true,
   :created_at=>"Sat Dec 03 06:08:21 +0000 2011",
   :lang=>"en",
   :profile_image_url_https=>
    "https://si0.twimg.com/sticky/default_profile_images/default_profile_5_normal.png",
   :contributors_enabled=>false,
   :statuses_count=>12,
   :description=>nil,
   :profile_background_color=>"C0DEED",
   :followers_count=>0,
   :utc_offset=>nil,
   :listed_count=>0,
   :default_profile=>true,
   :profile_link_color=>"0084B4",
   :following=>nil,
   :profile_background_image_url=>
    "http://a0.twimg.com/images/themes/theme1/bg.png",
   :time_zone=>nil,
   :url=>nil,
   :default_profile_image=>true,
   :protected=>false,
   :id_str=>"427170329",
   :location=>nil,
   :profile_sidebar_border_color=>"C0DEED",
   :friends_count=>0,
   :profile_background_image_url_https=>
    "https://si0.twimg.com/images/themes/theme1/bg.png",
   :verified=>false,
   :name=>"test rps",
   :id=>427170329,
   :favourites_count=>0,
   :profile_sidebar_fill_color=>"DDEEF6",
   :geo_enabled=>false,
   :profile_background_tile=>false},
 :truncated=>false,
 :text=>"rock_paper_scissors to the future5",
 :coordinates=>nil,
 :created_at=>"Sat Dec 03 21:20:06 +0000 2011",
 :geo=>nil,
 :entities=>{:hashtags=>[], :user_mentions=>[], :urls=>[]},
 :in_reply_to_user_id_str=>nil,
 :retweet_count=>0,
 :in_reply_to_screen_name=>nil,
 :contributors=>nil,
 :in_reply_to_status_id_str=>nil,
 :retweeted=>false,
 :id_str=>"143077071629979648",
 :place=>nil,
 :id=>143077071629979648,
 :source=>"web",
 :in_reply_to_status_id=>nil,
 :favorited=>false}